<?php

return [
    'roles' => [
        'super_admin' => 'Super Admin',
        'admin_desa' => 'Admin Desa',
        'operator' => 'Operator',
        'kepala_desa' => 'Kepala Desa',
        'warga' => 'Warga',
    ],

    'permissions' => [
        'super_admin' => ['*'],
        'admin_desa' => [
            'dashboard.view',
            'penduduk.view',
            'penduduk.manage',
            'penduduk.delete',
            'kk.view',
            'kk.manage',
            'surat.view',
            'surat.manage',
            'surat.print',
            'berita.view',
            'berita.manage',
            'bantuan.view',
            'bantuan.manage',
            'complaints.view',
            'complaints.create',
            'complaints.manage',
            'users.manage',
            'reports.view',
        ],
        'operator' => [
            'dashboard.view',
            'penduduk.view',
            'penduduk.manage',
            'kk.view',
            'kk.manage',
            'surat.view',
            'surat.manage',
            'surat.print',
            'berita.view',
            'berita.manage',
            'bantuan.view',
            'complaints.view',
            'complaints.create',
            'complaints.manage',
        ],
        'kepala_desa' => [
            'dashboard.view',
            'penduduk.view',
            'kk.view',
            'surat.view',
            'surat.print',
            'berita.view',
            'bantuan.view',
            'complaints.view',
            'reports.view',
        ],
        'warga' => [
            'dashboard.view',
            'surat.view',
            'berita.view',
            'complaints.view',
            'complaints.create',
        ],
    ],
];
